name: build

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: npm run lint
      - run: npm run test

  canary:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref != 'ref/head/main' && !contains(github.event.pull_request.labels.*.name, 'skip-release') }}
    environment: canary
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      checks: write
      issues: write
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY_URL: 'https://npm.pkg.github.com'
    steps:
      - uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.AUTO_PAT }}
      - run: git fetch --unshallow --tags
      - uses: ./.github/actions/setup-repo
      - run: npm run release
